# Generated by Django 3.0.8 on 2020-08-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200807_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'get_latest_by': '-created', 'ordering': ('-created',), 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
    ]
